version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Web management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Use the volume to persist RabbitMQ data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # MongoDB port
    environment:
      MONGO_INITDB_DATABASE: Reservation-service  # Initialize the database
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data

volumes:
  rabbitmq_data:
    driver: local  # Use the local volume driver

  mongodb_data:
    driver: local  # Use the local volume driver
